openapi: 3.0.1
info:
  title: Photobox.LocalServer
  version: "1.0"
servers:
- url: /
paths:
  /api/Application/ShutDown:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Application
  /api/Camera/Start:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Camera
  /api/Camera/Stop:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Camera
  /api/Camera/TakePicture:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TakePictureResultModel'
            application/json:
              schema:
                $ref: '#/components/schemas/TakePictureResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/TakePictureResultModel'
          description: OK
      tags:
      - Camera
  /api/Photobox/Print/{imagePath}:
    get:
      parameters:
      - explode: false
        in: path
        name: imagePath
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "403":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "415":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
      tags:
      - Photobox
  /api/Photobox/Save/{imagePath}:
    get:
      parameters:
      - explode: false
        in: path
        name: imagePath
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "403":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - Photobox
  /api/Photobox/Delete/{imagePath}:
    get:
      parameters:
      - explode: false
        in: path
        name: imagePath
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "403":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - Photobox
  /api/Settings/ListPrinters:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ListPrintersResultModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ListPrintersResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ListPrintersResultModel'
          description: OK
      tags:
      - Settings
  /api/Settings/GetPhotoboxSettings:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PhotoboxConfig'
            application/json:
              schema:
                $ref: '#/components/schemas/PhotoboxConfig'
            text/json:
              schema:
                $ref: '#/components/schemas/PhotoboxConfig'
          description: OK
      tags:
      - Settings
  /api/Settings/SetPrinter/{printerName}:
    get:
      parameters:
      - explode: false
        in: path
        name: printerName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      tags:
      - Settings
  /api/Settings/SetPrinterEnabled/{printerEnabled}:
    get:
      parameters:
      - explode: false
        in: path
        name: printerEnabled
        required: true
        schema:
          $ref: '#/components/schemas/PrinterEnabledOptions'
        style: simple
      responses:
        "200":
          description: OK
      tags:
      - Settings
  /api/Settings/PrintingEnabled:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PrintingEnabledResultModel'
            application/json:
              schema:
                $ref: '#/components/schemas/PrintingEnabledResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/PrintingEnabledResultModel'
          description: OK
      tags:
      - Settings
components:
  schemas:
    ListPrintersResultModel:
      additionalProperties: false
      example:
        printers:
        - printers
        - printers
      properties:
        printers:
          items:
            type: string
          nullable: true
          type: array
      type: object
    PhotoboxConfig:
      additionalProperties: false
      example:
        printingEnabled: "True"
        printerName: printerName
      properties:
        printingEnabled:
          $ref: '#/components/schemas/PrinterEnabledOptions'
        printerName:
          nullable: true
          type: string
      type: object
    PrinterEnabledOptions:
      enum:
      - "True"
      - "False"
      - Automatic
      type: string
    PrintingEnabledResultModel:
      additionalProperties: false
      example:
        printingEnabled: true
      properties:
        printingEnabled:
          type: boolean
      type: object
    ProblemDetails:
      additionalProperties: {}
      example:
        instance: instance
        detail: detail
        type: type
        title: title
        status: 0
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
      type: object
    TakePictureResultModel:
      additionalProperties: false
      example:
        imagePath: imagePath
      properties:
        imagePath:
          nullable: true
          type: string
      required:
      - imagePath
      type: object

