openapi: 3.0.1
info:
  title: Photobox.LocalServer
  version: "1.0"
servers:
- url: /
paths:
  /api/Application/ShutDown:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Application
  /api/Camera/Start:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Camera
  /api/Camera/Stop:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Camera
  /api/Camera/TakePicture:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TakePictureResultModel'
            application/json:
              schema:
                $ref: '#/components/schemas/TakePictureResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/TakePictureResultModel'
          description: OK
      tags:
      - Camera
  /api/Photobox/Print/{imagePath}:
    get:
      parameters:
      - explode: false
        in: path
        name: imagePath
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "403":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "415":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
      tags:
      - Photobox
  /api/Photobox/Save/{imagePath}:
    get:
      parameters:
      - explode: false
        in: path
        name: imagePath
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "403":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - Photobox
  /api/Photobox/Delete/{imagePath}:
    get:
      parameters:
      - explode: false
        in: path
        name: imagePath
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "403":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - Photobox
  /api/Photobox/PrinterConnected:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: boolean
            application/json:
              schema:
                type: boolean
            text/json:
              schema:
                type: boolean
          description: OK
      tags:
      - Photobox
components:
  schemas:
    ProblemDetails:
      additionalProperties: {}
      example:
        instance: instance
        detail: detail
        type: type
        title: title
        status: 0
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
      type: object
    TakePictureResultModel:
      additionalProperties: false
      example:
        imagePath: imagePath
      properties:
        imagePath:
          nullable: true
          type: string
      type: object

