# This is a generated file. Not intended for manual editing.
services:
  photobox.web:
    build:
      context: "C:\\Users\\Robin\\Documents\\GitHub\\Photobox"
      dockerfile: "Photobox.Web/Photobox.Web/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/Photobox.Web.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "photoboxweb:dev"
    ports:
    - "127.0.0.1:57005:57000"
    - "127.0.0.1:57205:57200"
    - "127.0.0.1:57405:57400"
    volumes:
    - "C:\\Users\\Robin\\Documents\\GitHub\\Photobox\\Photobox.Web\\Photobox.Web:/app:rw"
    - "C:\\Users\\Robin\\Documents\\GitHub\\Photobox:/src:rw"
    - "C:\\Users\\Robin\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Robin\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\Robin\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Robin\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_3_15_09_42_17:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
