/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Photobox.LocalServer.RestApi.Api;
using System;
using Xunit;
// uncomment below to import models
//using Photobox.LocalServer.RestApi.Model;

namespace Photobox.LocalServer.RestApi.Test.Api
{
    /// <summary>
    ///  Class for testing CameraApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CameraApiTests : IDisposable
    {
        private CameraApi instance;

        public CameraApiTests()
        {
            instance = new CameraApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CameraApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CameraApi
            //Assert.IsType<CameraApi>(instance);
        }

        /// <summary>
        /// Test ApiCameraStartGet
        /// </summary>
        [Fact]
        public void ApiCameraStartGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiCameraStartGet();
        }

        /// <summary>
        /// Test ApiCameraStopGet
        /// </summary>
        [Fact]
        public void ApiCameraStopGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiCameraStopGet();
        }

        /// <summary>
        /// Test ApiCameraTakePictureGet
        /// </summary>
        [Fact]
        public void ApiCameraTakePictureGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiCameraTakePictureGet();
            //Assert.IsType<TakePictureResultModel>(response);
        }
    }
}
