/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Photobox.LocalServer.RestApi.Api;
using System;
using Xunit;
// uncomment below to import models
//using Photobox.LocalServer.RestApi.Model;

namespace Photobox.LocalServer.RestApi.Test.Api
{
    /// <summary>
    ///  Class for testing PhotoboxApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PhotoboxApiTests : IDisposable
    {
        private PhotoboxApi instance;

        public PhotoboxApiTests()
        {
            instance = new PhotoboxApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhotoboxApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PhotoboxApi
            //Assert.IsType<PhotoboxApi>(instance);
        }

        /// <summary>
        /// Test ApiPhotoboxPrintImagePathGet
        /// </summary>
        [Fact]
        public void ApiPhotoboxPrintImagePathGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string imagePath = null;
            //instance.ApiPhotoboxPrintImagePathGet(imagePath);
        }
    }
}
