/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Photobox.LocalServer.RestApi.Api;
using System;
using Xunit;
// uncomment below to import models
//using Photobox.LocalServer.RestApi.Model;

namespace Photobox.LocalServer.RestApi.Test.Api
{
    /// <summary>
    ///  Class for testing SettingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SettingsApiTests : IDisposable
    {
        private SettingsApi instance;

        public SettingsApiTests()
        {
            instance = new SettingsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SettingsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SettingsApi
            //Assert.IsType<SettingsApi>(instance);
        }

        /// <summary>
        /// Test ApiSettingsGetPhotoboxSettingsGet
        /// </summary>
        [Fact]
        public void ApiSettingsGetPhotoboxSettingsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiSettingsGetPhotoboxSettingsGet();
            //Assert.IsType<PhotoboxConfig>(response);
        }

        /// <summary>
        /// Test ApiSettingsListPrintersGet
        /// </summary>
        [Fact]
        public void ApiSettingsListPrintersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiSettingsListPrintersGet();
            //Assert.IsType<ListPrintersResultModel>(response);
        }

        /// <summary>
        /// Test ApiSettingsPrintingEnabledGet
        /// </summary>
        [Fact]
        public void ApiSettingsPrintingEnabledGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiSettingsPrintingEnabledGet();
            //Assert.IsType<PrintingEnabledResultModel>(response);
        }

        /// <summary>
        /// Test ApiSettingsSetPrinterEnabledPrinterEnabledGet
        /// </summary>
        [Fact]
        public void ApiSettingsSetPrinterEnabledPrinterEnabledGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PrinterEnabledOptions printerEnabled = null;
            //instance.ApiSettingsSetPrinterEnabledPrinterEnabledGet(printerEnabled);
        }

        /// <summary>
        /// Test ApiSettingsSetPrinterPrinterNameGet
        /// </summary>
        [Fact]
        public void ApiSettingsSetPrinterPrinterNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerName = null;
            //instance.ApiSettingsSetPrinterPrinterNameGet(printerName);
        }
    }
}
