name: seq
services:
    seq:
        container_name: seq
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - SEQ_FIRSTRUN_ADMINPASSWORDHASH=$PH
        volumes:
            - ../../seq:/data
        ports:
            - 5341:80
        image: datalust/seq