networks:
  internal:


services:
  photobox.web:
    image: ${DOCKER_REGISTRY-}photoboxweb
    build:
      context: .
      dockerfile: Photobox.Web/Photobox.Web/Dockerfile
    networks:
      - "internal"
    depends_on:
      - postgres
    ports:
      - 443:8081

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: photobox
      POSTGRES_PASSWORD: (Kk3Db>+cJE5)r22!Yo
      POSTGRES_DB: PhotoboxDB
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - "internal"

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    ports:
#      - "8888:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: fotobox@muntafu.eu
#      PGADMIN_DEFAULT_PASSWORD: (Kk3Db>+cJE5)r22!Yo
#      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 10
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    depends_on:
#      - postgres
#    networks:
#      - "internal"
#
#  seq:
#    image: datalust/seq
#    restart: always
#    environment:
#      - ACCEPT_EULA=Y
#      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=
#    ports:
#      - "5341:80"
#    networks:
#      - "internal"
#    volumes:
#      - ./data/seq:/data

volumes:
  local_pgdata:
#  pgadmin-data:

  # loki:
  #   image: grafana/loki:master
  #   ports:
  #     - 3100:3100
  #   command: -config.file=/etc/loki/local-config.yaml
  #   healthcheck:
  #     test: wget -q --tries=1 -O- http://localhost:3100/ready
  #     interval: 3s
  #     timeout: 3s
  #     retries: 10
  #     start_period: 10s

  # grafana:
  #   image: grafana/grafana:master
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     loki:
  #       condition: service_healthy
  #   volumes:
  #     - ./data/grafana:/var/lib/grafana
  #     - ./data/grafana:/certs
