networks:
  internal:


services:
  photobox.web:
    image: ${DOCKER_REGISTRY-}photoboxweb
    build:
      context: .
      dockerfile: Photobox.Web/Photobox.Web/Dockerfile
    networks:
      - "internal"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: (K"k3Db>+cJE5)r22!Yo
      MYSQL_USER: photobox
      MYSQL_PASSWORD: (K"k3Db>+cJE5)r22!Yo
      MYSQL_DATABASE: PhotoboxDB
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - "internal"

  phpMyAdmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=photobox
      - PMA_PASSWORD=(K"k3Db>+cJE5)r22!Yo
    networks:
      - "internal"
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  seq:
    image: datalust/seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=
    ports:
      - "5341:80"
    networks:
      - "internal"
    volumes:
      - ./data/seq:/data

  # loki:
  #   image: grafana/loki:master
  #   ports:
  #     - 3100:3100
  #   command: -config.file=/etc/loki/local-config.yaml
  #   healthcheck:
  #     test: wget -q --tries=1 -O- http://localhost:3100/ready
  #     interval: 3s
  #     timeout: 3s
  #     retries: 10
  #     start_period: 10s

  # grafana:
  #   image: grafana/grafana:master
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     loki:
  #       condition: service_healthy
  #   volumes:
  #     - ./data/grafana:/var/lib/grafana
  #     - ./data/grafana:/certs
