/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace Photobox.LocalServer.RestApi.Test.Model
{
    /// <summary>
    ///  Class for testing ListPrintersResultModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListPrintersResultModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListPrintersResultModel
        //private ListPrintersResultModel instance;

        public ListPrintersResultModelTests()
        {
            // TODO uncomment below to create an instance of ListPrintersResultModel
            //instance = new ListPrintersResultModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListPrintersResultModel
        /// </summary>
        [Fact]
        public void ListPrintersResultModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListPrintersResultModel
            //Assert.IsType<ListPrintersResultModel>(instance);
        }

        /// <summary>
        /// Test the property 'Printers'
        /// </summary>
        [Fact]
        public void PrintersTest()
        {
            // TODO unit test for the property 'Printers'
        }
    }
}
