/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace Photobox.LocalServer.RestApi.Test.Model
{
    /// <summary>
    ///  Class for testing PhotoboxConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhotoboxConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhotoboxConfig
        //private PhotoboxConfig instance;

        public PhotoboxConfigTests()
        {
            // TODO uncomment below to create an instance of PhotoboxConfig
            //instance = new PhotoboxConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhotoboxConfig
        /// </summary>
        [Fact]
        public void PhotoboxConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhotoboxConfig
            //Assert.IsType<PhotoboxConfig>(instance);
        }

        /// <summary>
        /// Test the property 'PrintingEnabled'
        /// </summary>
        [Fact]
        public void PrintingEnabledTest()
        {
            // TODO unit test for the property 'PrintingEnabled'
        }

        /// <summary>
        /// Test the property 'PrinterName'
        /// </summary>
        [Fact]
        public void PrinterNameTest()
        {
            // TODO unit test for the property 'PrinterName'
        }
    }
}
