/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace Photobox.LocalServer.RestApi.Test.Model
{
    /// <summary>
    ///  Class for testing PrinterEnabledOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrinterEnabledOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrinterEnabledOptions
        //private PrinterEnabledOptions instance;

        public PrinterEnabledOptionsTests()
        {
            // TODO uncomment below to create an instance of PrinterEnabledOptions
            //instance = new PrinterEnabledOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrinterEnabledOptions
        /// </summary>
        [Fact]
        public void PrinterEnabledOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrinterEnabledOptions
            //Assert.IsType<PrinterEnabledOptions>(instance);
        }
    }
}
