/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace Photobox.LocalServer.RestApi.Test.Model
{
    /// <summary>
    ///  Class for testing PrintingEnabledResultModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrintingEnabledResultModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrintingEnabledResultModel
        //private PrintingEnabledResultModel instance;

        public PrintingEnabledResultModelTests()
        {
            // TODO uncomment below to create an instance of PrintingEnabledResultModel
            //instance = new PrintingEnabledResultModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrintingEnabledResultModel
        /// </summary>
        [Fact]
        public void PrintingEnabledResultModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrintingEnabledResultModel
            //Assert.IsType<PrintingEnabledResultModel>(instance);
        }

        /// <summary>
        /// Test the property 'PrintingEnabled'
        /// </summary>
        [Fact]
        public void PrintingEnabledTest()
        {
            // TODO unit test for the property 'PrintingEnabled'
        }
    }
}
