/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Photobox.LocalServer.RestApi.Model;
using Photobox.LocalServer.RestApi.Client;
using System.Reflection;
using Newtonsoft.Json;
using FluentAssertions;

namespace Photobox.LocalServer.RestApi.Test.Model
{
    /// <summary>
    ///  Class for testing TakePictureResultModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TakePictureResultModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TakePictureResultModel
        private TakePictureResultModel instance;

        public TakePictureResultModelTests()
        {
            // TODO uncomment below to create an instance of TakePictureResultModel
            instance = new TakePictureResultModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TakePictureResultModel
        /// </summary>
        [Fact]
        public void TakePictureResultModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TakePictureResultModel
            instance.Should().BeOfType<TakePictureResultModel>();
        }

        /// <summary>
        /// Test the property 'ImagePath'
        /// </summary>
        [Fact]
        public void ImagePathTest()
        {
            // TODO unit test for the property 'ImagePath'
        }
    }
}
