/*
 * Photobox.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Photobox.Web.RestApi.Client;
using Photobox.Web.RestApi.Api;

namespace Photobox.Web.RestApi.Test.Api
{
    /// <summary>
    ///  Class for testing ImageApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ImageApiTests : IDisposable
    {
        private ImageApi instance;

        public ImageApiTests()
        {
            instance = new ImageApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ImageApi
            //Assert.IsType<ImageApi>(instance);
        }

        /// <summary>
        /// Test ApiImageUploadPicturePost
        /// </summary>
        [Fact]
        public void ApiImageUploadPicturePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string imageName = null;
            //System.IO.Stream formFile = null;
            //instance.ApiImageUploadPicturePost(imageName, formFile);
        }
    }
}
