/*
 * Photobox.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Photobox.Web.RestApi.Client;
using Photobox.Web.RestApi.Api;

namespace Photobox.Web.RestApi.Test.Api
{
    /// <summary>
    ///  Class for testing PictureApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PictureApiTests : IDisposable
    {
        private PictureApi instance;

        public PictureApiTests()
        {
            instance = new PictureApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PictureApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PictureApi
            //Assert.IsType<PictureApi>(instance);
        }

        /// <summary>
        /// Test ApiPictureTestGet
        /// </summary>
        [Fact]
        public void ApiPictureTestGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filePath = null;
            //instance.ApiPictureTestGet(filePath);
        }

        /// <summary>
        /// Test ApiPictureUploadPicturePost
        /// </summary>
        [Fact]
        public void ApiPictureUploadPicturePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream formFile = null;
            //instance.ApiPictureUploadPicturePost(formFile);
        }
    }
}
