openapi: 3.0.1
info:
  title: Photobox.Web
  version: "1.0"
servers:
- url: /
paths:
  /api/Image/UploadImage:
    post:
      parameters:
      - explode: true
        in: query
        name: imageName
        required: false
        schema:
          type: string
        style: form
      requestBody:
        content:
          multipart/form-data:
            encoding:
              formFile:
                style: form
            schema:
              $ref: '#/components/schemas/_api_Image_UploadImage_post_request'
      responses:
        "200":
          description: OK
      tags:
      - Image
  /api/Image/GetImage/{imageName}:
    get:
      parameters:
      - explode: false
        in: path
        name: imageName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      tags:
      - Image
  /api/Image/ListImages:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  type: string
                type: array
            application/json:
              schema:
                items:
                  type: string
                type: array
            text/json:
              schema:
                items:
                  type: string
                type: array
          description: OK
      tags:
      - Image
  /api/Image/DeleteImages:
    delete:
      responses:
        "200":
          description: OK
      tags:
      - Image
components:
  schemas:
    _api_Image_UploadImage_post_request:
      properties:
        formFile:
          format: binary
          type: string
      type: object

