/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Photobox.LocalServer.RestApi.Model
{
    /// <summary>
    /// ListPrintersResultModel
    /// </summary>
    [DataContract(Name = "ListPrintersResultModel")]
    public partial class ListPrintersResultModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListPrintersResultModel" /> class.
        /// </summary>
        /// <param name="printers">printers.</param>
        public ListPrintersResultModel(List<string> printers = default(List<string>))
        {
            this.Printers = printers;
        }

        /// <summary>
        /// Gets or Sets Printers
        /// </summary>
        [DataMember(Name = "printers", EmitDefaultValue = true)]
        public List<string> Printers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListPrintersResultModel {\n");
            sb.Append("  Printers: ").Append(Printers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
