/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Photobox.LocalServer.RestApi.Model
{
    /// <summary>
    /// PrintingEnabledResultModel
    /// </summary>
    [DataContract(Name = "PrintingEnabledResultModel")]
    public partial class PrintingEnabledResultModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrintingEnabledResultModel" /> class.
        /// </summary>
        /// <param name="printingEnabled">printingEnabled.</param>
        public PrintingEnabledResultModel(bool printingEnabled = default(bool))
        {
            this.PrintingEnabled = printingEnabled;
        }

        /// <summary>
        /// Gets or Sets PrintingEnabled
        /// </summary>
        [DataMember(Name = "printingEnabled", EmitDefaultValue = true)]
        public bool PrintingEnabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrintingEnabledResultModel {\n");
            sb.Append("  PrintingEnabled: ").Append(PrintingEnabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
