/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;

namespace Photobox.LocalServer.RestApi.Model
{
    /// <summary>
    /// Defines PrinterEnabledOptions
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PrinterEnabledOptions
    {
        /// <summary>
        /// Enum True for value: True
        /// </summary>
        [EnumMember(Value = "True")]
        True = 1,

        /// <summary>
        /// Enum False for value: False
        /// </summary>
        [EnumMember(Value = "False")]
        False = 2,

        /// <summary>
        /// Enum Automatic for value: Automatic
        /// </summary>
        [EnumMember(Value = "Automatic")]
        Automatic = 3
    }

}
