/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Photobox.LocalServer.RestApi.Client;
using Photobox.LocalServer.RestApi.Model;

namespace Photobox.LocalServer.RestApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPhotoboxApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiPhotoboxDeleteImagePathGet(string imagePath, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiPhotoboxDeleteImagePathGetWithHttpInfo(string imagePath, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiPhotoboxPrintImagePathGet(string imagePath, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiPhotoboxPrintImagePathGetWithHttpInfo(string imagePath, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>bool</returns>
        bool ApiPhotoboxPrinterConnectedGet(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiPhotoboxPrinterConnectedGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiPhotoboxSaveImagePathGet(string imagePath, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiPhotoboxSaveImagePathGetWithHttpInfo(string imagePath, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPhotoboxApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiPhotoboxDeleteImagePathGetAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiPhotoboxDeleteImagePathGetWithHttpInfoAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiPhotoboxPrintImagePathGetAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiPhotoboxPrintImagePathGetWithHttpInfoAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiPhotoboxPrinterConnectedGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiPhotoboxPrinterConnectedGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiPhotoboxSaveImagePathGetAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiPhotoboxSaveImagePathGetWithHttpInfoAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPhotoboxApi : IPhotoboxApiSync, IPhotoboxApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PhotoboxApi : IPhotoboxApi
    {
        private Photobox.LocalServer.RestApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PhotoboxApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PhotoboxApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PhotoboxApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PhotoboxApi(string basePath)
        {
            this.Configuration = Photobox.LocalServer.RestApi.Client.Configuration.MergeConfigurations(
                Photobox.LocalServer.RestApi.Client.GlobalConfiguration.Instance,
                new Photobox.LocalServer.RestApi.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Photobox.LocalServer.RestApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Photobox.LocalServer.RestApi.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Photobox.LocalServer.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PhotoboxApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PhotoboxApi(Photobox.LocalServer.RestApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Photobox.LocalServer.RestApi.Client.Configuration.MergeConfigurations(
                Photobox.LocalServer.RestApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Photobox.LocalServer.RestApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Photobox.LocalServer.RestApi.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Photobox.LocalServer.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PhotoboxApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PhotoboxApi(Photobox.LocalServer.RestApi.Client.ISynchronousClient client, Photobox.LocalServer.RestApi.Client.IAsynchronousClient asyncClient, Photobox.LocalServer.RestApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Photobox.LocalServer.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Photobox.LocalServer.RestApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Photobox.LocalServer.RestApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Photobox.LocalServer.RestApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Photobox.LocalServer.RestApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiPhotoboxDeleteImagePathGet(string imagePath, int operationIndex = 0)
        {
            ApiPhotoboxDeleteImagePathGetWithHttpInfo(imagePath);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<Object> ApiPhotoboxDeleteImagePathGetWithHttpInfo(string imagePath, int operationIndex = 0)
        {
            // verify the required parameter 'imagePath' is set
            if (imagePath == null)
            {
                throw new Photobox.LocalServer.RestApi.Client.ApiException(400, "Missing required parameter 'imagePath' when calling PhotoboxApi->ApiPhotoboxDeleteImagePathGet");
            }

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("imagePath", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(imagePath)); // path parameter

            localVarRequestOptions.Operation = "PhotoboxApi.ApiPhotoboxDeleteImagePathGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/Photobox/Delete/{imagePath}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPhotoboxDeleteImagePathGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiPhotoboxDeleteImagePathGetAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await ApiPhotoboxDeleteImagePathGetWithHttpInfoAsync(imagePath, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<Object>> ApiPhotoboxDeleteImagePathGetWithHttpInfoAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'imagePath' is set
            if (imagePath == null)
            {
                throw new Photobox.LocalServer.RestApi.Client.ApiException(400, "Missing required parameter 'imagePath' when calling PhotoboxApi->ApiPhotoboxDeleteImagePathGet");
            }


            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("imagePath", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(imagePath)); // path parameter

            localVarRequestOptions.Operation = "PhotoboxApi.ApiPhotoboxDeleteImagePathGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/api/Photobox/Delete/{imagePath}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPhotoboxDeleteImagePathGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiPhotoboxPrintImagePathGet(string imagePath, int operationIndex = 0)
        {
            ApiPhotoboxPrintImagePathGetWithHttpInfo(imagePath);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<Object> ApiPhotoboxPrintImagePathGetWithHttpInfo(string imagePath, int operationIndex = 0)
        {
            // verify the required parameter 'imagePath' is set
            if (imagePath == null)
            {
                throw new Photobox.LocalServer.RestApi.Client.ApiException(400, "Missing required parameter 'imagePath' when calling PhotoboxApi->ApiPhotoboxPrintImagePathGet");
            }

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("imagePath", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(imagePath)); // path parameter

            localVarRequestOptions.Operation = "PhotoboxApi.ApiPhotoboxPrintImagePathGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/Photobox/Print/{imagePath}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPhotoboxPrintImagePathGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiPhotoboxPrintImagePathGetAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await ApiPhotoboxPrintImagePathGetWithHttpInfoAsync(imagePath, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<Object>> ApiPhotoboxPrintImagePathGetWithHttpInfoAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'imagePath' is set
            if (imagePath == null)
            {
                throw new Photobox.LocalServer.RestApi.Client.ApiException(400, "Missing required parameter 'imagePath' when calling PhotoboxApi->ApiPhotoboxPrintImagePathGet");
            }


            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("imagePath", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(imagePath)); // path parameter

            localVarRequestOptions.Operation = "PhotoboxApi.ApiPhotoboxPrintImagePathGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/api/Photobox/Print/{imagePath}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPhotoboxPrintImagePathGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>bool</returns>
        public bool ApiPhotoboxPrinterConnectedGet(int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.ApiResponse<bool> localVarResponse = ApiPhotoboxPrinterConnectedGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of bool</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<bool> ApiPhotoboxPrinterConnectedGetWithHttpInfo(int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "PhotoboxApi.ApiPhotoboxPrinterConnectedGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<bool>("/api/Photobox/PrinterConnected", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPhotoboxPrinterConnectedGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiPhotoboxPrinterConnectedGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Photobox.LocalServer.RestApi.Client.ApiResponse<bool> localVarResponse = await ApiPhotoboxPrinterConnectedGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<bool>> ApiPhotoboxPrinterConnectedGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "PhotoboxApi.ApiPhotoboxPrinterConnectedGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<bool>("/api/Photobox/PrinterConnected", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPhotoboxPrinterConnectedGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiPhotoboxSaveImagePathGet(string imagePath, int operationIndex = 0)
        {
            ApiPhotoboxSaveImagePathGetWithHttpInfo(imagePath);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<Object> ApiPhotoboxSaveImagePathGetWithHttpInfo(string imagePath, int operationIndex = 0)
        {
            // verify the required parameter 'imagePath' is set
            if (imagePath == null)
            {
                throw new Photobox.LocalServer.RestApi.Client.ApiException(400, "Missing required parameter 'imagePath' when calling PhotoboxApi->ApiPhotoboxSaveImagePathGet");
            }

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("imagePath", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(imagePath)); // path parameter

            localVarRequestOptions.Operation = "PhotoboxApi.ApiPhotoboxSaveImagePathGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/Photobox/Save/{imagePath}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPhotoboxSaveImagePathGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiPhotoboxSaveImagePathGetAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await ApiPhotoboxSaveImagePathGetWithHttpInfoAsync(imagePath, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="imagePath"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<Object>> ApiPhotoboxSaveImagePathGetWithHttpInfoAsync(string imagePath, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'imagePath' is set
            if (imagePath == null)
            {
                throw new Photobox.LocalServer.RestApi.Client.ApiException(400, "Missing required parameter 'imagePath' when calling PhotoboxApi->ApiPhotoboxSaveImagePathGet");
            }


            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("imagePath", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(imagePath)); // path parameter

            localVarRequestOptions.Operation = "PhotoboxApi.ApiPhotoboxSaveImagePathGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/api/Photobox/Save/{imagePath}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPhotoboxSaveImagePathGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
