/*
 * Photobox.LocalServer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Photobox.LocalServer.RestApi.Client;
using Photobox.LocalServer.RestApi.Model;
using System;

namespace Photobox.LocalServer.RestApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISettingsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PhotoboxConfig</returns>
        PhotoboxConfig ApiSettingsGetPhotoboxSettingsGet(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PhotoboxConfig</returns>
        ApiResponse<PhotoboxConfig> ApiSettingsGetPhotoboxSettingsGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ListPrintersResultModel</returns>
        ListPrintersResultModel ApiSettingsListPrintersGet(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ListPrintersResultModel</returns>
        ApiResponse<ListPrintersResultModel> ApiSettingsListPrintersGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PrintingEnabledResultModel</returns>
        PrintingEnabledResultModel ApiSettingsPrintingEnabledGet(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PrintingEnabledResultModel</returns>
        ApiResponse<PrintingEnabledResultModel> ApiSettingsPrintingEnabledGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerEnabled"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiSettingsSetPrinterEnabledPrinterEnabledGet(PrinterEnabledOptions printerEnabled, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerEnabled"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiSettingsSetPrinterEnabledPrinterEnabledGetWithHttpInfo(PrinterEnabledOptions printerEnabled, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiSettingsSetPrinterPrinterNameGet(string printerName, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiSettingsSetPrinterPrinterNameGetWithHttpInfo(string printerName, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISettingsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PhotoboxConfig</returns>
        System.Threading.Tasks.Task<PhotoboxConfig> ApiSettingsGetPhotoboxSettingsGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PhotoboxConfig)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhotoboxConfig>> ApiSettingsGetPhotoboxSettingsGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListPrintersResultModel</returns>
        System.Threading.Tasks.Task<ListPrintersResultModel> ApiSettingsListPrintersGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListPrintersResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListPrintersResultModel>> ApiSettingsListPrintersGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PrintingEnabledResultModel</returns>
        System.Threading.Tasks.Task<PrintingEnabledResultModel> ApiSettingsPrintingEnabledGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PrintingEnabledResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<PrintingEnabledResultModel>> ApiSettingsPrintingEnabledGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerEnabled"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiSettingsSetPrinterEnabledPrinterEnabledGetAsync(PrinterEnabledOptions printerEnabled, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerEnabled"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiSettingsSetPrinterEnabledPrinterEnabledGetWithHttpInfoAsync(PrinterEnabledOptions printerEnabled, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiSettingsSetPrinterPrinterNameGetAsync(string printerName, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiSettingsSetPrinterPrinterNameGetWithHttpInfoAsync(string printerName, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISettingsApi : ISettingsApiSync, ISettingsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SettingsApi : ISettingsApi
    {
        private Photobox.LocalServer.RestApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SettingsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SettingsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SettingsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SettingsApi(string basePath)
        {
            this.Configuration = Photobox.LocalServer.RestApi.Client.Configuration.MergeConfigurations(
                Photobox.LocalServer.RestApi.Client.GlobalConfiguration.Instance,
                new Photobox.LocalServer.RestApi.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Photobox.LocalServer.RestApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Photobox.LocalServer.RestApi.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Photobox.LocalServer.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SettingsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SettingsApi(Photobox.LocalServer.RestApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Photobox.LocalServer.RestApi.Client.Configuration.MergeConfigurations(
                Photobox.LocalServer.RestApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Photobox.LocalServer.RestApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Photobox.LocalServer.RestApi.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Photobox.LocalServer.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SettingsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SettingsApi(Photobox.LocalServer.RestApi.Client.ISynchronousClient client, Photobox.LocalServer.RestApi.Client.IAsynchronousClient asyncClient, Photobox.LocalServer.RestApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Photobox.LocalServer.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Photobox.LocalServer.RestApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Photobox.LocalServer.RestApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Photobox.LocalServer.RestApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Photobox.LocalServer.RestApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PhotoboxConfig</returns>
        public PhotoboxConfig ApiSettingsGetPhotoboxSettingsGet(int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.ApiResponse<PhotoboxConfig> localVarResponse = ApiSettingsGetPhotoboxSettingsGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PhotoboxConfig</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<PhotoboxConfig> ApiSettingsGetPhotoboxSettingsGetWithHttpInfo(int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsGetPhotoboxSettingsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<PhotoboxConfig>("/api/Settings/GetPhotoboxSettings", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsGetPhotoboxSettingsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PhotoboxConfig</returns>
        public async System.Threading.Tasks.Task<PhotoboxConfig> ApiSettingsGetPhotoboxSettingsGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Photobox.LocalServer.RestApi.Client.ApiResponse<PhotoboxConfig> localVarResponse = await ApiSettingsGetPhotoboxSettingsGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PhotoboxConfig)</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<PhotoboxConfig>> ApiSettingsGetPhotoboxSettingsGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsGetPhotoboxSettingsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PhotoboxConfig>("/api/Settings/GetPhotoboxSettings", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsGetPhotoboxSettingsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ListPrintersResultModel</returns>
        public ListPrintersResultModel ApiSettingsListPrintersGet(int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.ApiResponse<ListPrintersResultModel> localVarResponse = ApiSettingsListPrintersGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ListPrintersResultModel</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<ListPrintersResultModel> ApiSettingsListPrintersGetWithHttpInfo(int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsListPrintersGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<ListPrintersResultModel>("/api/Settings/ListPrinters", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsListPrintersGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListPrintersResultModel</returns>
        public async System.Threading.Tasks.Task<ListPrintersResultModel> ApiSettingsListPrintersGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Photobox.LocalServer.RestApi.Client.ApiResponse<ListPrintersResultModel> localVarResponse = await ApiSettingsListPrintersGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListPrintersResultModel)</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<ListPrintersResultModel>> ApiSettingsListPrintersGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsListPrintersGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ListPrintersResultModel>("/api/Settings/ListPrinters", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsListPrintersGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PrintingEnabledResultModel</returns>
        public PrintingEnabledResultModel ApiSettingsPrintingEnabledGet(int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.ApiResponse<PrintingEnabledResultModel> localVarResponse = ApiSettingsPrintingEnabledGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PrintingEnabledResultModel</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<PrintingEnabledResultModel> ApiSettingsPrintingEnabledGetWithHttpInfo(int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsPrintingEnabledGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<PrintingEnabledResultModel>("/api/Settings/PrintingEnabled", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsPrintingEnabledGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PrintingEnabledResultModel</returns>
        public async System.Threading.Tasks.Task<PrintingEnabledResultModel> ApiSettingsPrintingEnabledGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Photobox.LocalServer.RestApi.Client.ApiResponse<PrintingEnabledResultModel> localVarResponse = await ApiSettingsPrintingEnabledGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PrintingEnabledResultModel)</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<PrintingEnabledResultModel>> ApiSettingsPrintingEnabledGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsPrintingEnabledGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PrintingEnabledResultModel>("/api/Settings/PrintingEnabled", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsPrintingEnabledGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerEnabled"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiSettingsSetPrinterEnabledPrinterEnabledGet(PrinterEnabledOptions printerEnabled, int operationIndex = 0)
        {
            ApiSettingsSetPrinterEnabledPrinterEnabledGetWithHttpInfo(printerEnabled);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerEnabled"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<Object> ApiSettingsSetPrinterEnabledPrinterEnabledGetWithHttpInfo(PrinterEnabledOptions printerEnabled, int operationIndex = 0)
        {
            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("printerEnabled", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(printerEnabled)); // path parameter

            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsSetPrinterEnabledPrinterEnabledGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/Settings/SetPrinterEnabled/{printerEnabled}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsSetPrinterEnabledPrinterEnabledGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerEnabled"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiSettingsSetPrinterEnabledPrinterEnabledGetAsync(PrinterEnabledOptions printerEnabled, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await ApiSettingsSetPrinterEnabledPrinterEnabledGetWithHttpInfoAsync(printerEnabled, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerEnabled"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<Object>> ApiSettingsSetPrinterEnabledPrinterEnabledGetWithHttpInfoAsync(PrinterEnabledOptions printerEnabled, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("printerEnabled", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(printerEnabled)); // path parameter

            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsSetPrinterEnabledPrinterEnabledGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/api/Settings/SetPrinterEnabled/{printerEnabled}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsSetPrinterEnabledPrinterEnabledGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiSettingsSetPrinterPrinterNameGet(string printerName, int operationIndex = 0)
        {
            ApiSettingsSetPrinterPrinterNameGetWithHttpInfo(printerName);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Photobox.LocalServer.RestApi.Client.ApiResponse<Object> ApiSettingsSetPrinterPrinterNameGetWithHttpInfo(string printerName, int operationIndex = 0)
        {
            // verify the required parameter 'printerName' is set
            if (printerName == null)
            {
                throw new Photobox.LocalServer.RestApi.Client.ApiException(400, "Missing required parameter 'printerName' when calling SettingsApi->ApiSettingsSetPrinterPrinterNameGet");
            }

            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("printerName", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(printerName)); // path parameter

            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsSetPrinterPrinterNameGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/Settings/SetPrinter/{printerName}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsSetPrinterPrinterNameGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiSettingsSetPrinterPrinterNameGetAsync(string printerName, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await ApiSettingsSetPrinterPrinterNameGetWithHttpInfoAsync(printerName, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Photobox.LocalServer.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="printerName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Photobox.LocalServer.RestApi.Client.ApiResponse<Object>> ApiSettingsSetPrinterPrinterNameGetWithHttpInfoAsync(string printerName, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'printerName' is set
            if (printerName == null)
            {
                throw new Photobox.LocalServer.RestApi.Client.ApiException(400, "Missing required parameter 'printerName' when calling SettingsApi->ApiSettingsSetPrinterPrinterNameGet");
            }


            Photobox.LocalServer.RestApi.Client.RequestOptions localVarRequestOptions = new Photobox.LocalServer.RestApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Photobox.LocalServer.RestApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("printerName", Photobox.LocalServer.RestApi.Client.ClientUtils.ParameterToString(printerName)); // path parameter

            localVarRequestOptions.Operation = "SettingsApi.ApiSettingsSetPrinterPrinterNameGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/api/Settings/SetPrinter/{printerName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiSettingsSetPrinterPrinterNameGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
