# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    
    env:
      SOLUTION_FILE_PATH: ${{ github.workspace }}/src/Photobox.sln
      PROJECT_FILE_PATH: ${{ github.workspace }}/src/Photobox.UI/Photobox.UI.csproj
      TEST_FILE_PATH: ${{ github.workspace }}/src/Photobox.UI.Test/Photobox.UI.Test.csproj

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.PROJECT_FILE_PATH}}
    - name: Build
      run: dotnet build ${{env.PROJECT_FILE_PATH}} --no-restore
    - name: Test
      run: dotnet test ${{env.TEST_FILE_PATH}} --no-build --verbosity normal
